### ISSUE TITLE
Using proxy on HTTPS

### ISSUE THREAD

**Issue by dr3adx** [dmzubr/grafana-web-proxy#1]
Hello,

I set proxy to use HTTPS.

I get following output:
```
Now listening on: http://0.0.0.0:80
Now listening on: https://0.0.0.0:443
```

But my Iframes only work on http:80 port, while https:443 port gives "might be temporarily down or it may have moved permanently to a new web address."

Got any idea why this happens?

**Comment by dmzubr** [comment]
Hi there!

Right now to work with SSL need to configure certificate file.
When starting container use next ENV variables:
-- env GRAFANA_PROXY_USE_HTTPS=false
-- env GRAFANA_PROXY_PFX_FILENAME={Name of pfx file}
-- env GRAFANA_PROXY_PFX_PASS={Pass for your certificate}

Certificate file should be placed to the directory with executing files of app in container (/app).
So - you should build container with your cert file.

I suppose, that it would be better to pick up cert file from some mounted dir for container.
If so - please reply on this suggestion and I will implement this feature.

**Comment by dr3adx** [comment]
@dmzubr 

Nevermind, looks like it was problem with my SSL certificate after all.

**Comment by dmzubr** [comment]
> @dmzubr
> 
> Nevermind, looks like it was problem with my SSL certificate after all.

I can check on my side if need.

**Comment by dr3adx** [comment]
> > @dmzubr
> > Nevermind, looks like it was problem with my SSL certificate after all.
> 
> I can check on my side if need.

Not needed. I have it working.
Btw, would it be possible to specify API KEY via query string in case multiple users are supposed to use Grafana?

**Comment by dmzubr** [comment]
> > > @dmzubr
> > > Nevermind, looks like it was problem with my SSL certificate after all.
> > 
> > 
> > I can check on my side if need.
> 
> Not needed. I have it working.
> Btw, would it be possible to specify API KEY via query string in case multiple users are supposed to use Grafana?

Generally - of course it's possible.
But pass key directly over query string won't be a good idea from the point of security I suppose.
So - may be better to use some other source.

Could you please describe use case in details?
And based on this we'll try to make the most relevant solution.

**Comment by dr3adx** [comment]
> > > > @dmzubr
> > > > Nevermind, looks like it was problem with my SSL certificate after all.
> > > 
> > > 
> > > I can check on my side if need.
> > 
> > 
> > Not needed. I have it working.
> > Btw, would it be possible to specify API KEY via query string in case multiple users are supposed to use Grafana?
> 
> Generally - of course it's possible.
> But pass key directly over query string won't be a good idea from the point of security I suppose.
> So - may be better to use some other source.
> 
> Could you please describe use case in details?
> And based on this we'll try to make the most relevant solution.

Since there are different Grafana API Key types (viewer, editor, admin) there should be a way to access multiple API Keys over proxy. Query string might not be the most secure but it's easiest way to implement this.

**Comment by dmzubr** [comment]
> > > > > @dmzubr
> > > > > Nevermind, looks like it was problem with my SSL certificate after all.
> > > > 
> > > > 
> > > > I can check on my side if need.
> > > 
> > > 
> > > Not needed. I have it working.
> > > Btw, would it be possible to specify API KEY via query string in case multiple users are supposed to use Grafana?
> > 
> > 
> > Generally - of course it's possible.
> > But pass key directly over query string won't be a good idea from the point of security I suppose.
> > So - may be better to use some other source.
> > Could you please describe use case in details?
> > And based on this we'll try to make the most relevant solution.
> 
> Since there are different Grafana API Key types (viewer, editor, admin) there should be a way to access multiple API Keys over proxy. Query string might not be the most secure but it's easiest way to implement this.

I suppose that it's relevant to use API key for the organization entity in Grafana.
But, anyway, of course there could be a lot of organizations.

May be better to use some static keys or usernames and API keys associated with them.
With initialization like the following:
-- env GRAFANA_USERS_LIST="dr3adx:api_key_1,dmzubr:api_key_2".

And pass only user name in query string?
What do you think on this?

Another options is to pass on Authorization header - but this requires more logic on the client side to work with them.

**Comment by dr3adx** [comment]
@dmzubr 

I think first approach is good.
- env GRAFANA_USERS_LIST="dr3adx:api_key_1,dmzubr:api_key_2".

And if no query string is passed then default to first key in the list

**Comment by dmzubr** [comment]
Exactly.
Ok, I'll implement this.

ср, 10 июн. 2020 г., 2:42 dr3adx <notifications@github.com>:

**Comment by dmzubr** [comment]
> @dmzubr
> 
> I think first approach is good.
> 
> * env GRAFANA_USERS_LIST="dr3adx:api_key_1,dmzubr:api_key_2".
> 
> And if no query string is passed then default to first key in the list

Hi there!

You can check this:
https://github.com/dmzubr/grafana-web-proxy/commit/efa0f11b80df1cb2b7a69a4c8384a17a4fcd55e5

Docker image is also updated.

**Comment by dr3adx** [comment]
> > @dmzubr
> > I think first approach is good.
> > 
> > * env GRAFANA_USERS_LIST="dr3adx:api_key_1,dmzubr:api_key_2".
> > 
> > And if no query string is passed then default to first key in the list
> 
> Hi there!
> 
> You can check this:
> [efa0f11](https://github.com/dmzubr/grafana-web-proxy/commit/efa0f11b80df1cb2b7a69a4c8384a17a4fcd55e5)
> 
> Docker image is also updated.

Thanks a lot I appreciate it. This is very helpful.

I hate to ask this since you did so much already, but would it be possible to add support for multiple Grafana endpoints too? And select it the same way via query string

e.g &proxy_grafanaId=grafana1
where grafana endpoints are specified the same way like GRAFANA_USERS env
"endpoint1:url1,endpoint2:url2" 
example => "grafana1:https://test.grafana.com,grafana2:https://test2.grafana.com"

This would be so helpful instead of running multiple docker images for each grafana endpoint

**Comment by dmzubr** [comment]
> > > @dmzubr
> > > I think first approach is good.
> > > 
> > > * env GRAFANA_USERS_LIST="dr3adx:api_key_1,dmzubr:api_key_2".
> > > 
> > > And if no query string is passed then default to first key in the list
> > 
> > 
> > Hi there!
> > You can check this:
> > [efa0f11](https://github.com/dmzubr/grafana-web-proxy/commit/efa0f11b80df1cb2b7a69a4c8384a17a4fcd55e5)
> > Docker image is also updated.
> 
> Thanks a lot I appreciate it. This is very helpful.
> 
> I hate to ask this since you did so much already, but would it be possible to add support for multiple Grafana endpoints too? And select it the same way via query string
> 
> e.g &proxy_grafanaId=grafana1
> where grafana endpoints are specified the same way like GRAFANA_USERS env
> "endpoint1:url1,endpoint2:url2"
> example => "grafana1:https://test.grafana.com,grafana2:https://test2.grafana.com"
> 
> This would be so helpful instead of running multiple docker images for each grafana endpoint

No problem.

Could you please open another issue with this idea? To close this one.
